# Generated by Django 4.2.3 on 2023-07-31 07:43

import core.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=core.models.LowercaseEmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
