# Generated by Django 4.2.3 on 2023-08-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="productimages"
            ),
        ),
    ]
