# Generated by Django 4.2.3 on 2023-08-09 09:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_premiumproduct"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="premiumproduct",
            options={},
        ),
    ]
