# Generated by Django 4.2.3 on 2023-08-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_premiumproduct_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="premiumproduct",
            options={
                "permissions": (
                    (
                        "can_avail_premium_delivery",
                        "can avail for premium delivery on premium products",
                    ),
                    (
                        "can_add_premium_discount",
                        "can avail more premium discount on premium products",
                    ),
                )
            },
        ),
        migrations.AlterField(
            model_name="premiumproduct",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="premiumproductimages"
            ),
        ),
    ]
